//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPIsmagilov
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KPIsmagilovEntities : DbContext
    {
        public KPIsmagilovEntities()
            : base("name=KPIsmagilovEntities")
        {
        }

        private static KPIsmagilovEntities _context;

        public static KPIsmagilovEntities GetContext()
        {
            if (_context == null)
                _context = new KPIsmagilovEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Navy_bases> Navy_bases { get; set; }
        public virtual DbSet<Personnel> Personnel { get; set; }
        public virtual DbSet<Ships> Ships { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teachings> Teachings { get; set; }
        public virtual DbSet<Units> Units { get; set; }
    }
}
