//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPIsmagilov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teachings
    {
        public int IDTeachings { get; set; }
        public int IDShip { get; set; }
        public int IDUnits { get; set; }
        public System.DateTime DateTeachings { get; set; }
        public string Venue { get; set; }
        public string Grade { get; set; }
    
        public virtual Ships Ships { get; set; }
        public virtual Units Units { get; set; }
    }
}
